In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

Phase 1 : Numpy array and basics learnabout numpy with chai aur code.

In [6]:
#Creating array from list.
arr_1d = np.array([4,8,9])
arr_2d = np.array([[7,8,9], [55,11,44]])

print("One dimension array : ",arr_1d)
print("Two dimension array : ",arr_2d)

One dimension array :  [4 8 9]
Two dimension array :  [[ 7  8  9]
 [55 11 44]]


In [12]:
#Difference in list and numpy array
list_1 = [1,2,3,4]
arr_1 = np.array([1,2,3,4])

print("List multiplication : ", list_1*2)
print("Array multiplication : ", arr_1*2)

import time

start = time.time()
list_2 = [i*2 for i in range(1000000)]
print("Time for list operation : ",time.time()- start)

start = time.time()
arr_2 = np.arange(1000000)*2
print("Time for array operation : ",time.time()- start)


List multiplication :  [1, 2, 3, 4, 1, 2, 3, 4]
Array multiplication :  [2 4 6 8]
Time for list operation :  0.11070060729980469
Time for array operation :  0.0048978328704833984


In [17]:
#Creating array from scratch.
zero_arr = np.zeros((3,5))
print(zero_arr)

one_arr = np.ones((3,5))
print(one_arr)

constant_arr = np.full((3,5),5)
print(constant_arr)

random_arr = np.random.random((3,5))
print(random_arr)

sequence_arr = np.arange(0,21,2)
print(sequence_arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[0.83243008 0.00505117 0.46514869 0.21713139 0.62908146]
 [0.61179244 0.81911046 0.076575   0.65098548 0.96574148]
 [0.90887776 0.40216532 0.90953928 0.41838524 0.87868059]]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [19]:
#Vector, matrices, tensors:
vector_arr = np.array([1,2,3,4,5])
matrix_arr = np.array([[1,2,3,4,5],
                      [6,7,8,9,10]])
tensor_arr = np.array([[[1,2,3], [4,5,6]],
                      [[7,8,9], [10,11,12]]])

print(vector_arr)
print(matrix_arr)
print(tensor_arr)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [21]:
#Array properties

array = np.array([[4, 5, 6], [7, 8, 9]])
print("Shape : ",array.shape)
print("Dimension : ",array.ndim)
print("Size : ",array.size)
print("Data type : ", array.dtype)

Shape :  (2, 3)
Dimension :  2
Size :  6
Data type :  int64


In [25]:
#Array reshaping

array = np.arange(1,10)
print("Original : ",array)

reshaped = array.reshape((3,3))
print("Reshaped : ",reshaped)

flatten = reshaped.flatten()
print("Flattened : ",flatten)

#ravel - changes in original array
print("Raveled : ",reshaped.ravel())
print("Reshaped : ",reshaped)


transpose = reshaped.T
print("Transpose : ",transpose)

Original :  [1 2 3 4 5 6 7 8 9]
Reshaped :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened :  [1 2 3 4 5 6 7 8 9]
Raveled :  [1 2 3 4 5 6 7 8 9]
Reshaped :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose :  [[1 4 7]
 [2 5 8]
 [3 6 9]]


Phase 2 : Numpy array operations

In [27]:
#Indexing and slicing

arr = np.arange(10)
print(arr)

print("Basic slicing [3,6] : ",arr[3:6])
print("Slicing with step : ",arr[1:8:2])
print("Last fourth element : ",arr[-4])

[0 1 2 3 4 5 6 7 8 9]
Basic slicing [3,6] :  [3 4 5]
Slicing with step :  [1 3 5 7]
Last fourth element :  6


In [31]:
arr_2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("specific element : ",arr_2d[2,1])
print("Entire row : ",arr_2d[1])
print("Enire column : ",arr_2d[:, 0])

specific element :  8
Entire row :  [4 5 6]
Enire column :  [1 4 7]


In [40]:
#Sorting
unsorted = np.random.randint(100, size=10)
print("Unsorted : ",unsorted)
print("Sorted : \n",np.sort(unsorted))

unsorted_2d = np.random.randint(100, size=(3,4))
print("Unsorted 2D : \n",unsorted_2d)
print("Sorted 2D by column : \n",np.sort(unsorted_2d, axis=0))
print("Sorted 2D by row : \n",np.sort(unsorted_2d, axis=1))

Unsorted :  [16 61  9 80 67 32 36  6 66 80]
Sorted : 
 [ 6  9 16 32 36 61 66 67 80 80]
Unsorted 2D : 
 [[15 16 63 55]
 [48 21 48 45]
 [77 99 46 84]]
Sorted 2D by column : 
 [[15 16 46 45]
 [48 21 48 55]
 [77 99 63 84]]
Sorted 2D by row : 
 [[15 16 55 63]
 [21 45 48 48]
 [46 77 84 99]]


In [50]:
#Filtering
arr_1 = np.random.randint(50, size=10)
print("Original array : ",arr_1)
print("Even numbers : ",arr_1[arr_1 % 2 == 0])

mask = arr_1 > 5
print("Numbers greater than 5 : ",arr_1[mask])

where_result = np.where(arr_1 > 5) #where stores indices
print(where_result)
print("Numbers greater than 5 (Using where) : ",arr_1[where_result])

conditioning_arr = np.where(arr_1 > 5, 'T', 'F')
#np.where(if : arr_1 > 5, then : 'T', else : 'F')
print("Numbers greater than 5 (True or False) : ",conditioning_arr)

Original array :  [13  9 39  5 17 40 36  7  3 18]
Even numbers :  [40 36 18]
Numbers greater than 5 :  [13  9 39 17 40 36  7 18]
(array([0, 1, 2, 4, 5, 6, 7, 9]),)
Numbers greater than 5 (Using where) :  [13  9 39 17 40 36  7 18]
Numbers greater than 5 (True or False) :  ['T' 'T' 'T' 'F' 'T' 'T' 'T' 'T' 'F' 'T']


In [60]:
#Adding and removing data
arr_1 = np.random.randint(50, size=10)
print(arr_1)
arr_2 = np.random.randint(50, size=10)
print(arr_2)

print("Addition : ", arr_1 + arr_2)
print("Concatenation : ", np.concatenate((arr_1, arr_2)))
print("Adding row : ",np.vstack((arr_1, arr_2)))
print("Adding column : ",np.hstack((arr_1.T, arr_2.T)))
print("Array after deleting first element : ",np.delete(arr_1,0))

[49 20  8 22  6 22  1 31 24 43]
[49 44 20 40 35  8 46 11  0 16]
Addition :  [98 64 28 62 41 30 47 42 24 59]
Concatenation :  [49 20  8 22  6 22  1 31 24 43 49 44 20 40 35  8 46 11  0 16]
Adding row :  [[49 20  8 22  6 22  1 31 24 43]
 [49 44 20 40 35  8 46 11  0 16]]
Adding column :  [49 20  8 22  6 22  1 31 24 43 49 44 20 40 35  8 46 11  0 16]
Array after deleting first element :  [20  8 22  6 22  1 31 24 43]


In [56]:
#Array compatibility
print("Compatibility test : ", arr_1.shape==arr_2.shape)

Compatibility test :  True


Phase 3 : Advance operation with business examples

In [3]:
#Create dummy database
#column_names = ["restaurant_id", 2021, 2022, 2023, 2024]

sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],
    [2, 120000, 140000, 160000, 200000],
    [3, 50000, 70000, 80000, 120000],
    [4, 500000, 510000, 530000, 495000],
    [5, 200000, 210000, 220000, 230000]
])

print("=== Sales analysis ===")
print("Shape of data : ",sales_data.shape)
print("First 3 restaurant data : \n",sales_data[:3])
print("Sales per year : \n", np.sum(sales_data[:, 1:], axis=0))

print("Minimum sales per restaurant : \n", np.min(sales_data[:, 1:], axis=1))
print("Maximum sales per restaurant : \n", np.max(sales_data[:, 1:], axis=1))

print("Minimum sales per year : \n", np.min(sales_data[:, 1:], axis=0))
print("Maximum sales per year : \n", np.max(sales_data[:, 1:], axis=0))

print("Average sales per restaurant : \n", np.mean(sales_data[:, 1:], axis=1))
print("Average sales per year : \n", np.mean(sales_data[:, 1:], axis=0))

=== Sales analysis ===
Shape of data :  (5, 5)
First 3 restaurant data : 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 200000]
 [     3  50000  70000  80000 120000]]
Sales per year : 
 [1020000 1110000 1210000 1295000]
Minimum sales per restaurant : 
 [150000 120000  50000 495000 200000]
Maximum sales per restaurant : 
 [250000 200000 120000 530000 230000]
Minimum sales per year : 
 [ 50000  70000  80000 120000]
Maximum sales per year : 
 [500000 510000 530000 495000]
Average sales per restaurant : 
 [200000. 155000.  80000. 508750. 215000.]
Average sales per year : 
 [204000. 222000. 242000. 259000.]


In [7]:
#Vector operations
vector_1 = np.random.randint(10,size=5)
print(vector_1)
vector_2 = np.random.randint(10,size=5)
print(vector_2)

print("Vector addition : ",vector_1 + vector_2)
print("Vector multiplication : ",vector_1 * vector_2)
print("Vector dot product : ",np.dot(vector_1, vector_2))
print("Angle between two vectors : ",np.arccos(np.dot(vector_1, vector_2) / (np.linalg.norm(vector_1) * np.linalg.norm(vector_2))))

[8 9 2 5 9]
[5 6 2 0 2]
Vector addition :  [13 15  4  5 11]
Vector multiplication :  [40 54  4  0 18]
Vector dot product :  116
Angle between two vectors :  0.5063776478350427


In [8]:
#Vectorize operations
arr = ['a', 'b', 'c', 'd', 'e']
vectorized_upper = np.vectorize(str.upper) #You can write any normal python function instead of 'str.upper'
print(vectorized_upper(arr))

['A' 'B' 'C' 'D' 'E']
